apiVersion: v1
kind: Pod              # tipo de recurso
metadata:
  name: nginx          # nome do Pod
spec:
  containers:
  - name: nginx        # nome do container
    image: nginx:1.14.2 # imagem usada
    ports:
    - containerPort: 80 # porta exposta no container