apiVersion: apps/v1
kind: Deployment
metadata:
  name: primeira-aplicacao
  namespace: aplicacao      # namespace dedicado
  labels:
    app: ruby
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby
  template:
    metadata:
      labels:
        app: ruby
    spec:
      containers:
      - name: primeira-aplicacao
        image: eduardoajs2020/primeira-aplicacao:2.0  # sua imagem
        ports:
        - containerPort: 80
 