
apiVersion: v1

kind: Service

metadata:

  name: produtos-api

  labels:

    app: produtos-api

spec:

  type: NodePort

  selector:

    app: produtos-api

  ports:

    - name: http

      port: 8080

      targetPort: 8080

      nodePort: 30080

