
services:

  postgres:

    image: postgres:16

    container_name: produtos-postgres

    environment:

      POSTGRES_DB: produtosdb

      POSTGRES_USER: admin

      POSTGRES_PASSWORD: admin123

    ports:

      - "5432:5432"

    networks:

      - produtos-network


  api:

    image: produtos-api:v1

    container_name: produtos-api

    depends_on:

      - postgres

    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/produtosdb

      SPRING_DATASOURCE_USERNAME: admin

      SPRING_DATASOURCE_PASSWORD: admin123

    ports:

      - "8080:8080"

    networks:

      - produtos-network


networks:

  produtos-network:

    driver: bridge

